export const PODCAST_IDEAS = [
    'Your podcast should be about the benefits of waffles for dinner',
    'Your podcast should be about announcements on public transit',
    'Your podcast should be about Coke versus Pepsi',
    'Your podcast should be about zip-off cargo shorts',
    'Your podcast should be about how to avoid doing work in group projects',
    'Your podcast should be about saying I Love You for the first time',
    'Your podcast should be about what percentage your phone should be on before you charge it',
    'Your podcast should be about making a work best friend',
    'Your podcast should be about triumphing over your fear of asking for a special order at In N Out',
    'Your podcast should be about social media in 2021',
    'Your podcast should be about accidently replying all',
    'Your podcast should be about the feeling of walking into work and discovering your boss is out for the day',
    'Your podcast should be about your favorite brand of cozy clothes',
    'Your podcast should be about living in the most temperate place on Earth',
    'Your podcast should be about shapes of clouds that look like pop stars',
    'Your podcast should be about the best songs to sing in the shower',
    'Your podcast should be about medium-sized dogs',
    'Your podcast should be about the beach versus the mountains',
    'Your podcast should be about how to find a new dentist',
    'Your podcast should be about animals that escape from zoos',
    'Your podcast should be about common superstitions and where they come from',
    'Your podcast should be about the best kind of weather for reading a book indoors',
    'Your podcast should be about the proper amount of floss length',
    'Your podcast should be about the tooth fairy',
    'Your podcast should be about Disney films',
    'Your podcast should be about chocolate vs. potato chips vs. chocolate covered potatoe chips',
    'Your podcast should be about libraries vs. bookstores',
    'Your podcast should be about electronic scooters',
    'Your podcast should be about reading 52 books in 52 weeks',
    "Your podcast should be about things that haven't even been invented yet ",
    'Your podcast should be about making meaningful memories',
    'Your podcast should be about how to fold a fitted sheet',
    "Your podcast should be about movie theaters' revenue streams ",
    'Your podcast should be about how to start a farm',
    'Your podcast should be about the creation of the railroad system',
    'Your podcast should be about recapping every episode of a TV show you love',
    'Your podcast should be about the rise of wedding photography industry',
    'Your podcast should be about reviews of concert reviews',
    'Your podcast should be about unusual weather events',
    'Your podcast should be about the best coffee shops in your state',
    'Your podcast should be about teacup collections in history',
    'Your podcast should be about how to write a song a day',
    'Your podcast should be about how to surf while living in Nebraska',
    'Your podcast should be about shark sightings',
    'Your podcast should be about miniature horses and tiny houses',
    'Your podcast should be about arts and crafts for adults',
    'Your podcast should be about naming nail polish colors',
    'Your podcast should be about the best gear to use to climb Everest ',
    'Your podcast should be about juiceboxes and jukeboxes ',
    "Your podcast should be about 80's pop music and 90's rom-coms",
    'Your podcast should be about classic Broadway shows',
    'Your podcast should be about rural architecture',
    'Your podcast should be about running marathons barefoot',
    'Your podcast should be about how to shower in less than 3 minutes',
    "Your podcast should be about Pluto's hurt feelings",
    'Your podcast should be about folk music festivals',
    'Your podcast should be about journaling once a year',
    'Your podcast should be about 1800s medicine',
    'Your podcast should be about time travel',
    'Your podcast should be about ice cream versus cake at birthday parties ',
    'Your podcast should be about the Spice Girls',
    'Your podcast should be about cheese wheels',
    'Your podcast should be about how often to change your phone case',
    'Your podcast should be about Saturday morning cartoons',
    'Your podcast should be about the price of stamps over time',
    'Your podcast should be about massive sticker collections',
    'Your podcast should be about giraffes and pigeons',
    'Your podcast should be about finding the perfect shade of yellow paint',
    'Your podcast should be about your favorite holiday traditions to sleep through',
    'Your podcast should be about creating the perfect brunch menu',
    'Your podcast should be about beauty and joy',
    'Your podcast should be about how cats rule the internet',
    'Your podcast should be about having a pig as a pet',
    'Your podcast should be about lions, tigers, and bears',
    'Your podcast should be about bananas and other fruit that double as a telephone',
    'Your podcast should be about your favorite football team',
    'Your podcast should be about learning to fly a helicopter',
    'Your podcast should be about how to change a tire in a hurry',
    'Your podcast should be about how to care for houseplants',
    'Your podcast should be about deep sea fishing and romantic gestures',
    'Your podcast should be about corn mazes and Google maps',
    'Your podcast should be about unhealthy eating',
    'Your podcast should be about traveling internationally without leaving the country',
    'Your podcast should be about pretending to understand the economy',
    'Your podcast should be about spotted frogs and polka dots',
    'Your podcast should be about earthquake reporting',
    'Your podcast should be about how to buy comic books',
    'Your podcast should be about your favorite sculpter ',
    'Your podcast should be about snow day activities',
    'Your podcast should be about yard sale sales tactics ',
    'Your podcast should be about learning to draw with your non-dominant hand',
    'Your podcast should be about selling doll clothes on the internet',
    'Your podcast should be about collecting old records',
    'Your podcast should be about tugboat travel',
]
