/* eslint import/prefer-default-export: 0 */
export const LANGUAGES = [
    { value: 'English', text: 'English' },
    { value: 'Mandarin', text: 'Mandarin' },
    { value: 'Spanish', text: 'Spanish' },
    { value: 'Hindi', text: 'Hindi' },
    { value: 'Russian', text: 'Russian' },
    { value: 'Arabic', text: 'Arabic' },
    { value: 'Portuguese', text: 'Portuguese' },
    { value: 'Bengali', text: 'Bengali' },
    { value: 'French', text: 'French' },
    { value: 'Mala', text: 'Mala' },
    { value: 'German', text: 'German' },
    { value: 'Japanese', text: 'Japanese' },
    { value: 'Farsi', text: 'Farsi' },
    { value: 'Urdu', text: 'Urdu' },
    { value: 'Punjabi', text: 'Punjabi' },
    { value: 'Wu', text: 'Wu' },
    { value: 'Vietnamese', text: 'Vietnamese' },
    { value: 'Javanese', text: 'Javanese' },
    { value: 'Tamil', text: 'Tamil' },
    { value: 'Korean', text: 'Korean' },
    { value: 'Turkish', text: 'Turkish' },
    { value: 'Telugu', text: 'Telugu' },
    { value: 'Marathi', text: 'Marathi' },
    { value: 'Italian', text: 'Italian' },
    { value: 'Thai', text: 'Thai' },
    { value: 'Burmese', text: 'Burmese' },
    { value: 'Cantonese', text: 'Cantonese' },
    { value: 'Kannada', text: 'Kannada' },
    { value: 'Gujarati', text: 'Gujarati' },
    { value: 'Polish', text: 'Polish' },
]
